deadlines:
  '2':
    Wed`:
      date: 2026/05/13 6:00pm EST 
      content: ip1
  '2':
    Fri:
      date: 2026/05/15 6:00pm EST 
      content: tp1
  '3':
    Wed:
      date: 2026/05/20 6:00pm EST
      content: ip2
  '3':
    Fri:
      date: 2026/05/22 6:00pm EST
      content: tp2
  '4':
    Wed:
      date: 2026/05/27 6:00pm EST
      content: ip3
  '5':
    Mon:
      date: 2026/06/01 6:00pm EST
      content: tp3
  '7':
    Tue:
      date: 2026/06/16 6:00pm EST
      content: tp4
  '7':
    Fri:
      date: 2026/06/19 6:00pm EST
      content: tp5
dates:
  firstMonday: 2026/05/04
  numWeeks: 7
types:
  default:
    className: lesson
  holiday:
    className: holiday